log:
  level: debug

plugins:
  - tag: cn_forward
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: https://223.5.5.5/dns-query
        - addr: https://1.12.12.12/dns-query
  - tag: non_cn_forward
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: https://8.8.8.8/dns-query
          socks5: 127.0.0.1:1081
        - addr: https://1.1.1.1/dns-query
          socks5: 127.0.0.1:1081
  - tag: forward_with_fallback
    type: fallback
    args:
      primary: non_cn_forward
      secondary: cn_forward
      threshold: 3000
      always_standby: false
  - tag: default_entry
    type: sequence
    args:
      - exec: query_summary
      - exec: cache
      - matches:
          - qname &geosite_cn.txt &geosite_google@cn.txt &geosite_apple@cn.txt
        exec: $cn_forward
      - matches:
          - qname &geosite_cn.txt &geosite_google@cn.txt &geosite_apple@cn.txt
        exec: return
      - matches:
          - qname &geosite_geolocation-!cn.txt
        exec: $forward_with_fallback
      - matches:
          - qname &geosite_geolocation-!cn.txt
        exec: return
      - exec: $cn_forward
  - tag: udp4_server
    type: udp_server
    args:
      entry: default_entry
      listen: 127.0.0.1:53
  - tag: udp6_server
    type: udp_server
    args:
      entry: default_entry
      listen: "[::1]:53"
  - tag: tcp4_server
    type: tcp_server
    args:
      entry: default_entry
      listen: 127.0.0.1:53
  - tag: tcp6_server
    type: tcp_server
    args:
      entry: default_entry
      listen: "[::1]:53"

api:
  http: 127.0.0.1:9080
