log:
  level: debug

plugins:
  - tag: default_entry
    type: sequence
    args:
      - exec: query_summary
      - exec: cache
      - exec: forward https://223.5.5.5/dns-query https://1.12.12.12/dns-query
  - tag: udp4_server
    type: udp_server
    args:
      entry: default_entry
      listen: 127.0.0.1:53
  - tag: udp6_server
    type: udp_server
    args:
      entry: default_entry
      listen: "[::1]:53"
  - tag: tcp4_server
    type: tcp_server
    args:
      entry: default_entry
      listen: 127.0.0.1:53
  - tag: tcp6_server
    type: tcp_server
    args:
      entry: default_entry
      listen: "[::1]:53"

api:
  http: 127.0.0.1:9080
