log:
  level: debug

plugins:
  - tag: default_cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400

  - tag: cn_forward
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: alidns
          addr: https://223.5.5.5/dns-query
        - tag: dnspod
          addr: https://120.53.53.53/dns-query
  - tag: non_cn_forward_with_proxy
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: google
          addr: https://8.8.8.8/dns-query
          socks5: 127.0.0.1:1081
        - tag: cloudflare
          addr: https://1.1.1.1/dns-query
          socks5: 127.0.0.1:1081
  - tag: non_cn_forward_without_proxy
    type: forward
    args:
      concurrent: 4
      upstreams:
        - tag: cloudflare
          addr: https://1.0.0.1/dns-query
        - tag: quad9
          addr: https://9.9.9.9/dns-query
        - tag: opendns
          addr: https://208.67.222.222/dns-query
        - tag: dns_sb
          addr: https://185.222.222.222/dns-query
  - tag: non_cn_forward_with_fallback
    type: fallback
    args:
      primary: non_cn_forward_with_proxy
      secondary: non_cn_forward_without_proxy
      threshold: 1000
      always_standby: false

  - tag: cn_forward_sequence
    type: sequence
    args:
      - exec: $cn_forward
  - tag: non_cn_forward_sequence
    type: sequence
    args:
      - exec: $non_cn_forward_with_fallback
  - tag: sysu_forward_sequence
    type: sequence
    args:
      - exec: forward 10.8.8.8 10.8.4.4

  - tag: pre_query
    type: sequence
    args:
      - exec: query_summary
      - exec: $default_cache
      - matches:
          - has_resp
        exec: accept
  - tag: default_query
    type: sequence
    args:
      - matches:
          - "qname &geosite-cn.txt &gfwlist-whitelist.txt"
        exec: goto cn_forward_sequence
      - matches:
          - "qname &gfwlist.txt"
        exec: goto non_cn_forward_sequence
      - exec: $cn_forward
  - tag: default_entry
    type: sequence
    args:
      - exec: jump pre_query
      - exec: jump default_query
  - tag: sysu_entry
    type: sequence
    args:
      - exec: jump pre_query
      - matches:
          - qname sysu.edu.cn
        exec: goto sysu_forward_sequence
      - exec: jump default_query

  - tag: default_udp_server
    type: udp_server
    args:
      entry: default_entry
      listen: 127.0.0.1:53
  - tag: default_tcp_server
    type: tcp_server
    args:
      entry: default_entry
      listen: 127.0.0.1:53
  - tag: sysu_udp_server
    type: udp_server
    args:
      entry: sysu_entry
      listen: 127.0.1.0:53
  - tag: sysu_tcp_server
    type: tcp_server
    args:
      entry: sysu_entry
      listen: 127.0.1.0:53

api:
  http: 127.0.0.1:9080
